name: test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go: [ '1.18' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    env:
      GO111MODULE: "on"

    steps:
      - uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Install dependencies
        run: go mod tidy

      - name: Test
        run: go test -covermode=count -coverprofile="coverprofile.cov"  ./...

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS }}
        run: |
          go get github.com/mattn/goveralls
          go run github.com/mattn/goveralls -coverprofile="coverprofile.cov" -service=github